version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build: .
    tty: true
    env_file: .env
    entrypoint: ["/opt/entrypoint.sh"]
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/app
    links:
      - redis
    depends_on:
      - redis